version: "3.9"
services:
  redis:
    env_file:
      - .env
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  postgres:
    image: postgres:14.2
    env_file:
      - .env
    ports:
      - 5432:5432
  auth:
    build:
      context: .
      dockerfile: Dockerfile_auth
    env_file:
      - .env
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    # entrypoint: >
    #   sh -c "ls -la /code/utils"
    entrypoint: >
      sh -c "poetry run /code/utils/wait_for_redis.py &&
            poetry run flask db upgrade &&
            poetry run gunicorn main:app"
