version: "3.9"
services:
  postgres:
    image: postgres:14.2
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    env_file:
      - .env
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6379:6379
