version: "3.9"
services:
  redis:
    env_file:
      - .env.docker
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  postgres:
    image: postgres:14.2
    env_file:
      - .env.docker
    ports:
      - 5432:5432
  auth:
    build:
      context: .
    env_file:
      - .env.docker
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    entrypoint: /code/entrypoint.sh
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - auth
